require 'faker'

def seed_neighborhoods
  puts "Seeding Neighborhoods"
  Neighborhood.create(name: "Ballard", character: "Urban", picture: "ballard.jpg")
  Neighborhood.create(name: "West Seattle", character: "Coastal", picture: "wseattle.jpg")
  Neighborhood.create(name: "Downtown Seattle", character: "Urban", picture: "downtown.jpg")
  Neighborhood.create(name: "Capitol Hill", character: "Urban", picture: "caphill.jpg")
  Neighborhood.create(name: "Queen Anne", character: "Urban", picture: "queenanne.jpg")
  Neighborhood.create(name: "Lake City", character: "Urban", picture: "lakecity.png")
  Neighborhood.create(name: "University District", character: "Urban", picture: "udistrict.jpg")
  Neighborhood.create(name: "Wallingford", character: "Urban", picture: "wallingford.jpg")
  Neighborhood.create(name: "Shoreline", character: "Suburban", picture: "shoreline.jpg")
  puts "Neighborhoods successfully seeded"
end

def seed_users
  puts "Seeding Users"
  20.times do 
    puts "Creating User"
    User.create!(name: Faker::Name.name, email: Faker::Internet.email, password: "password", neighborhood_id: Neighborhood.all.sample.id)
    puts "Successfully Created User"
  end
end

def seed_raccoons
  raccoon_pictures = ["raccoon1.jpg", "raccoon2.jpg", "raccoon3.jpg", "raccoon4.jpg", "raccoon5.jpg", "raccoon6.jpg", "raccoon7.jpg", "raccoon8.jpg", "raccoon9.jpg", "raccoon10.jpg", "raccoon11.jpg", "raccoon12.jpg", "raccoon13.jpg", "raccoon14.jpg", "raccoon15.jpg", "raccoon16.jpg", "raccoon17.jpg", "raccoon18.jpg", "raccoon19.jpg", "raccoon20.jpg", "raccoon21.jpg", "raccoon22.jpg", "raccoon23.jpg", "raccoon24.jpg", "raccoon25.jpg", "raccoon26.jpg", "raccoon27.jpg", "raccoon28.jpg", "raccoon29.jpg", "raccoon30.jpg", "raccoon31.jpg", "raccoon32.jpg", "raccoon33.jpg", "raccoon34.jpg", "raccoon35.jpg", "raccoon36.jpg", "raccoon37.jpg", "raccoon38.jpg", "raccoon39.jpg", "raccoon40.jpg", "raccoon41.jpg", "raccoon42.jpg", "raccoon43.jpg", "raccoon44.jpg", "raccoon45.jpg", "raccoon46.jpg", "raccoon47.jpg", "raccoon48.jpg", "raccoon49.jpg", "raccoon50.jpg", "raccoon51.jpg" ]
  puts "Seeding Raccoons"
  (1..51).each { |val|
    puts "Creating Raccoon"
    Raccoon.create!(name: Faker::Name.first_name, color: ["Brown", "Black", "Tan", "Grey", "White", "Red"].sample, size: ["small", "medium", "large", "massive"].sample, gender: Faker::Gender.binary_type, favorite_food: Faker::Food.dish, disposition: ["friendly", "shy", "aggressive", "loving", "defensive"].sample, user_id: User.all.sample.id, picture: raccoon_pictures[val-1])
    puts "Successfully Created Raccoon"
  }
end

#Ballard Locations
def seed_ballard
  puts "Seeding Ballard"
  Location.create!(neighborhood_id: 1, address: "2011 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2034 NW 61st St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2009 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2829 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1770 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2853 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5603 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2011 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2034 NW 61st St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2009 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2829 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1770 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2853 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5603 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2011 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2034 NW 61st St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2009 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2829 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1770 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2853 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5603 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2011 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2034 NW 61st St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2009 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2829 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1770 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2853 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5603 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2011 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2034 NW 61st St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2009 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2829 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1770 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2853 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5603 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2011 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2034 NW 61st St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2009 NW 64th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2829 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1770 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2853 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5603 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2643 NW 56th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2227 NW 60th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2410 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1525 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5803 24th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2428 NW 63rd St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1711 NW 65th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2601 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1713 NW 65th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1525 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1763 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1761 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5616 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1751 NW 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2410 NW 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1525 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5803 24th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2428 NW 63rd St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1711 NW 65th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "2601 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1713 NW 65th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1525 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1763 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1761 NW 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "5616 28th Ave NW, Seattle, WA")
  Location.create!(neighborhood_id: 1, address: "1751 NW 59th St, Seattle, WA")
  puts "Ballard Successfully Seeded"
end

# #West Seattle Locations
def seed_west_seattle
  puts "Seeding West Seattle"
  Location.create!(neighborhood_id: 2, address: "4563 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4016 45th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3619 50th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4563 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4016 45th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3619 50th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4563 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4016 45th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3619 50th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4563 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4016 45th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3619 50th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4563 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4016 45th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3619 50th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4563 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4016 45th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3619 50th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3625 47th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4110 39th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4801 SW Hinds St, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3221 SW Avalon Way, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3720 41st Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4006 35th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3318 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "2734 Garlough Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "5243 SW Stevens St, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3261 30th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4706 SW Stevens St, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3261 40th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "2913 39th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3648 44th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4444 44th SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "2742 36th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3213 Harbor Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3234 48th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3261 37th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3613 35th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3423 35th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4014 48th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3035 46th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "2742 36th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3213 Harbor Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3234 48th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3261 37th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3613 35th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3423 35th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "4014 48th Ave SW, Seattle, WA")
  Location.create!(neighborhood_id: 2, address: "3035 46th Ave SW, Seattle, WA")
  puts "West Seattle Successfully Seeded"
end

# #Downtown Seattle
def seed_downtown
  puts "Seeding Downtown Seattle"
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1425 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1425 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1425 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1425 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1425 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1425 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1119 1st Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1500 4th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2000 1st Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "737 Olive Way, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "737 Olive Way, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "737 Olive Way, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "909 5th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "909 5th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1107 1st Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2021 1st Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2030 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2030 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "909 5th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "909 5th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "909 5th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1107 1st Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "1415 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2021 1st Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 2nd Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2033 Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2030 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "2030 Western Ave, Seattle, WA")
  Location.create!(neighborhood_id: 3, address: "909 5th Ave, Seattle, WA")
  puts "Downtown Seattle Successfully Seeded"
end

# #Capitol Hill Locations
def seed_cap_hill
  puts "Seeding Capitol Hill"
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "200 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "516 E Thomas St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1709 18th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "232 Belmont Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1200 E Republican St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "410 10th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1624 E Mercer St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "601 14th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1802 15th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1410 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "921 18th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "211 Summit Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1732 15th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1610 Belmont Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "510 Malden Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "111 13th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "412 10th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "120 21st Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "525 Belmont Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1111 E Pike St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "150 Melrose Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "732 Belmont Pl E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1728 17th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "303 16th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "923 10th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "752 Bellevue Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "714 Bellevue Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1812 12th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "422 11th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1806 12th Ave, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "214 Summit Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "124 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1554 17th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "225 Harvard Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "231 Harvard Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "700 E Denny Way, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1128 10th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1128 10th Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "417 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "417 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "417 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "417 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "417 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "417 E Pine St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "700 E Denny Way, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "917 Harvard Ave E, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1210 E John St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1210 E John St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1210 E John St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1210 E John St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1210 E John St, Seattle, WA")
  Location.create!(neighborhood_id: 4, address: "1210 E John St, Seattle, WA")
  puts "Capitol Hill Successfully Seeded"
end
#Queen Anne Locations
def seed_queen_anne
  puts "Seeding Queen Anne"
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "500 W Olympic Pl, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "217 W Prospect St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1401 5th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "400 W Mcgraw Pl, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1508 1st Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1415 7th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1404 W Boston St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "117 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2604 Mayfair Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2625 13th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2625 13th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2506 1st Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1504 1st Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1003 W Prospect St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1937 4th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "109 Newell St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2110 2nd Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1013 W Howe St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2200 11th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1937 4th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "109 Newell St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2110 2nd Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1013 W Howe St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "2200 11th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "500 W Olympic Pl, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "217 W Prospect St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1401 5th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "400 W Mcgraw Pl, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1508 1st Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "204 Garfield St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "500 W Olympic Pl, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "217 W Prospect St, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1401 5th Ave W, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "400 W Mcgraw Pl, Seattle, WA")
  Location.create!(neighborhood_id: 5, address: "1508 1st Ave N, Seattle, WA")
  puts "Successfully Seeded Queen Anne"
end

#Lake City Locations
def seed_lake_city
  puts "Seeding Lake City Locations"
  Location.create!(neighborhood_id: 6, address: "13770 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13506 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13511 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13733 20th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13325 31st Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13310 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13728 28th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13351 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "2801 NE 130th St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13024 23rd Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13770 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13506 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13511 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13733 20th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13308 23rd Pl NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13742 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13338 20th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13723 28th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13723 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "3036 NE 133rd St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13028 28th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13044 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13531 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13704 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "2738 NE 135th St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13505 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13343 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "12726 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13047 31st Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13021 23rd Pl NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "2602 NE 140th St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13045 26th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13820 26th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13535 23rd Pl NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13343 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "12726 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13047 31st Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13021 23rd Pl NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "2602 NE 140th St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13045 26th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13820 26th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13535 23rd Pl NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13044 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13531 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13704 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "2738 NE 135th St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13505 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13343 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "12726 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13047 31st Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13044 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13531 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13704 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "2738 NE 135th St, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13505 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13343 30th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "12726 27th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 6, address: "13047 31st Ave NE, Seattle, WA")
  puts "Successsfully Seeded Lake City"
end

def seed_ud
  puts "Seeding University District Locations"
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5114 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5108 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "844 NE 59th St, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5110 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5324 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4725 15th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4706 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5806 16th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4734 17th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "823 NE 57th St, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5109 Ravenna Pl NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5116 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5112 24th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "856 NE 56th St, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5328 7th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5611 University Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5306 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4204 11th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5322 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5440 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4343 Roosevelt Way NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5331 8th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "5260 12th Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 7, address: "4708 18th Ave NE, Seattle, WA")
  puts "Successfully Seeded University District"
end

def seed_wallingford
  puts "Seeding Wallinford Locations"
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3811 Corliss Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4912 Stone Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3401 Wallingford Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2356 N 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2112 N 38th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5218 Kensington Pl N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5012 Latona Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5710 Latona Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5710 Latona Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "337 NE 56th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4227 1st Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4111 Interlake Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "1419 N 53rd St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3401 Wallingford Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3931 2nd Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4027 Latona Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3811 Ashworth Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "1223 N 49th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "154 NE 53rd St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5639 Kirkwood Pl N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3939 Burke Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4741 Latona Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2401 N Northlake Way, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3333 Wallingford Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3811 Corliss Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4912 Stone Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3401 Wallingford Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2356 N 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2112 N 38th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5218 Kensington Pl N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5639 Kirkwood Pl N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3939 Burke Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4741 Latona Ave NE, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2401 N Northlake Way, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3333 Wallingford Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "323 NE 55th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3811 Corliss Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4912 Stone Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3811 Corliss Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "4912 Stone Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "3401 Wallingford Ave N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2356 N 58th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "2112 N 38th St, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5218 Kensington Pl N, Seattle, WA")
  Location.create!(neighborhood_id: 8, address: "5639 Kirkwood Pl N, Seattle, WA")
  puts "Successfully Seeded Wallingford"
end

def seed_shoreline
  puts "Seeding Shoreline Locations"
  Location.create!(neighborhood_id: 8, address: "1024 NE 180th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1620 N 200th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18331 12th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "17611 Ashworth Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2324 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2132 N 146th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "14717 23rd Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18121 12th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1551 NW 195th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "19224 Firlands Way N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "19315 11th Ave NW, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1416 NW 195th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1145 N 166th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "19335 11th Ave NW, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18224 24th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2322 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "108 N 183rd St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "15554 Ashworth Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18545 Fremont Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "14539 28th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2322 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2324 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "19517 21st Pl NW, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "17521 Densmore Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2355 NE 150th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "16747 Ashworth Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1234 NE Ballinger Pl, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "16709 Fremont Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "17512 Densmore Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1812 NW 202nd St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "17550 Wallingford Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "20005 12th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "20235 21st Ave NW, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1416 NW 195th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1145 N 166th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "19335 11th Ave NW, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18224 24th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2322 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "108 N 183rd St, Shoreline, WA")
  Location.create!(neighborhood_id: 8, address: "1024 NE 180th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1620 N 200th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18331 12th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "17611 Ashworth Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2324 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1416 NW 195th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1145 N 166th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "19335 11th Ave NW, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18224 24th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2322 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 8, address: "1024 NE 180th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1620 N 200th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18331 12th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "17611 Ashworth Ave N, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2324 N 185th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "2132 N 146th St, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "14717 23rd Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "18121 12th Ave NE, Shoreline, WA")
  Location.create!(neighborhood_id: 9, address: "1551 NW 195th St, Shoreline, WA")
  puts "Successfully Seeded Shoreline"
end

# seed_locations
def seed_locations
  seed_ballard
  seed_west_seattle
  seed_downtown
  seed_cap_hill
  seed_queen_anne
  seed_lake_city
  seed_ud
  seed_wallingford
  seed_shoreline
end

#seed reports
def seed_reports
  puts "Seeding Reports"
  
  Location.all.each do |location|
    puts "Creating Report"
    Report.create!(time: Faker::Date.backward(730), user_id: User.all.sample.id, location_id: location.id)
    puts "Successfully Created Report"
  end
  # 100.times do 
  #   puts "Creating Report"
  #   Report.create!(time: Faker::Date.backward(730), user_id: User.all.sample.id, location_id: Location.all.sample.id)
  #   puts "Successfully Created Report"
  # end
end

def seed_raccoon_parties
  puts "Seeding Raccoon Parties"
  2000.times do 
    puts "Raccoon Party!!!!!!"
    RaccoonParty.create(raccoon_id: Raccoon.all.sample.id, report_id: Report.all.sample.id)
  end
  puts "Raccoon Parties have ended :(..."
end

seed_neighborhoods
seed_users
seed_raccoons
seed_locations
seed_reports
seed_raccoon_parties
